// SPDX-FileCopyrightText: 2026 Jorge Pérez Burgueño and Nodus contributors
// SPDX-License-Identifier: AGPL-3.0-only
import type { CategorizedReleaseHighlight } from './releaseNotes';

/** Final user-visible outcomes from v5.7.3..f7521ffd. Pre-release iterations are included in each final feature. */
export const RELEASE_5_7_4_HIGHLIGHTS: CategorizedReleaseHighlight[] = [
  {
    "category": "new",
    "scope": "toolkit",
    "es": "PDF Presenter permite controlar una presentación con la app de iPhone/iPad mediante un código QR en macOS, Windows y Linux. La app recibe las diapositivas y las notas, y permite navegar, usar el puntero y controlar el temporizador y los vídeos. En Windows y Linux ambos dispositivos deben estar en la misma red local. También puedes seguir usando el control desde el navegador.",
    "en": "PDF Presenter lets you control a presentation with the iPhone/iPad app by scanning a QR code on macOS, Windows and Linux. The app receives slides and notes and lets you navigate, use the pointer and control the timer and videos. On Windows and Linux, both devices must be on the same local network. Browser control remains available.",
    "fr": "PDF Presenter permet de contrôler une présentation avec l’app iPhone/iPad en scannant un code QR sur macOS, Windows et Linux. L’app reçoit les diapositives et les notes et permet de naviguer, d’utiliser le pointeur et de contrôler le minuteur et les vidéos. Sur Windows et Linux, les deux appareils doivent être sur le même réseau local. Le contrôle depuis le navigateur reste disponible.",
    "de": "Mit PDF Presenter steuern Sie eine Präsentation über die iPhone/iPad-App per QR-Code auf macOS, Windows und Linux. Die App empfängt Folien und Notizen und bietet Navigation, Zeiger sowie Steuerung von Timer und Videos. Unter Windows und Linux müssen beide Geräte im selben lokalen Netzwerk sein. Die Steuerung über den Browser bleibt verfügbar.",
    "pt": "O PDF Presenter permite controlar uma apresentação com a aplicação para iPhone/iPad através de um código QR no macOS, Windows e Linux. A aplicação recebe os diapositivos e as notas e permite navegar, usar o ponteiro e controlar o temporizador e os vídeos. No Windows e Linux, ambos os dispositivos têm de estar na mesma rede local. O controlo pelo navegador continua disponível.",
    "pt-BR": "O PDF Presenter permite controlar uma apresentação com o app para iPhone/iPad por um código QR no macOS, Windows e Linux. O app recebe os slides e as notas e permite navegar, usar o ponteiro e controlar o temporizador e os vídeos. No Windows e Linux, os dois dispositivos precisam estar na mesma rede local. O controle pelo navegador continua disponível.",
    "it": "PDF Presenter permette di controllare una presentazione con l’app per iPhone/iPad tramite un codice QR su macOS, Windows e Linux. L’app riceve diapositive e note e permette di navigare, usare il puntatore e controllare il timer e i video. Su Windows e Linux entrambi i dispositivi devono essere sulla stessa rete locale. Il controllo dal browser resta disponibile.",
    "tr": "PDF Presenter, macOS, Windows ve Linux üzerinde QR kodunu tarayarak iPhone/iPad uygulamasıyla sunumu kontrol etmenizi sağlar. Uygulama slaytları ve notları alır, gezinme, işaretçi, zamanlayıcı ve video kontrolleri sunar. Windows ve Linux üzerinde iki cihaz aynı yerel ağda olmalıdır. Tarayıcıdan kontrol de kullanılabilir.",
    "zh-CN": "PDF Presenter 支持在 macOS、Windows 和 Linux 上扫描二维码，使用 iPhone/iPad 应用控制演示。应用接收幻灯片和备注，并提供翻页、指针、计时器和视频控制。在 Windows 和 Linux 上，两台设备须位于同一局域网。仍可通过浏览器控制。",
    "zh-TW": "PDF Presenter 支援在 macOS、Windows 和 Linux 上掃描 QR 碼，使用 iPhone/iPad App 控制簡報。App 接收投影片和備註，並提供翻頁、指標、計時器和影片控制。在 Windows 和 Linux 上，兩台裝置須位於同一區域網路。仍可透過瀏覽器控制。",
    "ja": "PDF Presenterは、macOS、Windows、LinuxでQRコードを読み取り、iPhone/iPadアプリからプレゼンテーションを操作できます。アプリにスライドとノートが届き、ページ移動、ポインター、タイマー、動画を操作できます。WindowsとLinuxでは両方の端末を同じローカルネットワークに接続してください。ブラウザーからの操作も引き続き使えます。",
    "ko": "PDF Presenter는 macOS, Windows, Linux에서 QR 코드를 스캔하여 iPhone/iPad 앱으로 발표를 제어할 수 있습니다. 앱은 슬라이드와 노트를 받아 페이지 이동, 포인터, 타이머, 동영상 제어를 제공합니다. Windows와 Linux에서는 두 기기가 같은 로컬 네트워크에 있어야 합니다. 브라우저 제어도 계속 사용할 수 있습니다."
  },
  {
    "category": "new",
    "scope": "library",
    "es": "La extracción de texto puede simplificar esquemas de reacción y fragmentos de figuras en nuevos PDF, conservando el texto principal, los pies de figura y las referencias. La opción está activada por defecto en Ajustes, Extracción de texto. Los documentos ya procesados conservan su extracción anterior.",
    "en": "Text extraction can simplify reaction schemes and figure fragments in new PDFs while preserving body text, captions and references. The option is enabled by default in Settings, Text extraction. Previously processed documents keep their existing extraction.",
    "fr": "L’extraction de texte peut simplifier les schémas réactionnels et les fragments de figures dans les nouveaux PDF, tout en conservant le texte principal, les légendes et les références. L’option est activée par défaut dans Réglages, Extraction de texte. Les documents déjà traités conservent leur extraction précédente.",
    "de": "Die Textextraktion kann Reaktionsschemata und Abbildungsfragmente in neuen PDFs vereinfachen und dabei Fließtext, Bildunterschriften und Quellenangaben erhalten. Die Option ist unter Einstellungen, Textextraktion standardmäßig aktiviert. Bereits verarbeitete Dokumente behalten ihre bisherige Extraktion.",
    "pt": "A extração de texto pode simplificar esquemas de reação e fragmentos de figuras em novos PDF, preservando o texto principal, as legendas e as referências. A opção está ativa por predefinição em Definições, Extração de texto. Os documentos já processados mantêm a extração anterior.",
    "pt-BR": "A extração de texto pode simplificar esquemas de reação e fragmentos de figuras em novos PDFs, preservando o texto principal, as legendas e as referências. A opção está ativada por padrão em Configurações, Extração de texto. Os documentos já processados mantêm a extração anterior.",
    "it": "L’estrazione del testo può semplificare schemi di reazione e frammenti di figure nei nuovi PDF, conservando testo principale, didascalie e riferimenti. L’opzione è attiva per impostazione predefinita in Impostazioni, Estrazione del testo. I documenti già elaborati mantengono l’estrazione precedente.",
    "tr": "Metin çıkarma, yeni PDF’lerdeki tepkime şemalarını ve şekil parçalarını sadeleştirirken ana metni, açıklamaları ve kaynakları koruyabilir. Bu seçenek Ayarlar, Metin çıkarma bölümünde varsayılan olarak açıktır. Daha önce işlenen belgeler mevcut çıkarılmış metni korur.",
    "zh-CN": "文本提取可简化新 PDF 中的反应示意图和插图片段，同时保留正文、图注和参考文献。该选项在“设置、文本提取”中默认启用。已处理的文档保留原有提取结果。",
    "zh-TW": "文字擷取可簡化新 PDF 中的反應示意圖和插圖片段，同時保留內文、圖說和參考文獻。此選項在「設定、文字擷取」中預設啟用。已處理的文件保留原有擷取結果。",
    "ja": "新しいPDFのテキスト抽出で、本文、図の説明、参考文献を残しながら反応スキームや図の断片を簡略化できます。設定のテキスト抽出で標準で有効になっています。処理済みの文書は以前の抽出結果を保持します。",
    "ko": "텍스트 추출은 새 PDF의 반응 도식과 그림 조각을 단순화하면서 본문, 그림 설명, 참고문헌을 보존할 수 있습니다. 설정의 텍스트 추출에서 기본으로 활성화됩니다. 이미 처리한 문서는 기존 추출 결과를 유지합니다."
  },
  {
    "category": "enhancement",
    "scope": "toolkit",
    "es": "PDF Presenter organiza las presentaciones en carpetas y subcarpetas. Puedes buscarlas, moverlas con el menú o arrastrarlas, y elegir si conservar sus copias al eliminar una carpeta. Las etiquetas anteriores se convierten en carpetas sin perder notas ni vídeos. En el modo presentador puedes ajustar el espacio de las vistas de diapositivas y las notas.",
    "en": "PDF Presenter organizes presentations in folders and subfolders. Search them, move them with the menu or drag them, and choose whether to keep their copies when deleting a folder. Existing tags become folders without losing notes or videos. In presenter mode, you can resize the slide previews and notes area.",
    "fr": "PDF Presenter organise les présentations en dossiers et sous-dossiers. Recherchez-les, déplacez-les avec le menu ou par glisser-déposer et choisissez de conserver leurs copies lors de la suppression d’un dossier. Les anciennes étiquettes deviennent des dossiers sans perdre notes ni vidéos. En mode présentateur, les aperçus et la zone de notes sont redimensionnables.",
    "de": "PDF Presenter organisiert Präsentationen in Ordnern und Unterordnern. Sie können sie suchen, über das Menü oder per Ziehen verschieben und beim Löschen eines Ordners ihre Kopien behalten. Bisherige Tags werden zu Ordnern, ohne Notizen oder Videos zu verlieren. Im Präsentationsmodus lassen sich Folienvorschauen und Notizbereich in der Größe anpassen.",
    "pt": "O PDF Presenter organiza apresentações em pastas e subpastas. Pode pesquisá-las, movê-las pelo menu ou arrastá-las e escolher se mantém as cópias ao eliminar uma pasta. As etiquetas anteriores tornam-se pastas sem perder notas nem vídeos. No modo de apresentador pode ajustar o espaço das pré-visualizações e das notas.",
    "pt-BR": "O PDF Presenter organiza apresentações em pastas e subpastas. Você pode buscá-las, movê-las pelo menu ou arrastá-las e escolher se mantém as cópias ao excluir uma pasta. As etiquetas anteriores viram pastas sem perder notas nem vídeos. No modo apresentador, é possível ajustar o espaço das prévias dos slides e das notas.",
    "it": "PDF Presenter organizza le presentazioni in cartelle e sottocartelle. Puoi cercarle, spostarle dal menu o trascinarle e scegliere se conservarne le copie quando elimini una cartella. Le etichette precedenti diventano cartelle senza perdere note o video. In modalità relatore puoi ridimensionare le anteprime e l’area delle note.",
    "tr": "PDF Presenter sunumları klasörler ve alt klasörler içinde düzenler. Arama yapabilir, menüden veya sürükleyerek taşıyabilir ve klasör silinirken kopyaları korumayı seçebilirsiniz. Eski etiketler, notlar ve videolar kaybolmadan klasörlere dönüşür. Sunucu modunda slayt önizlemelerinin ve not alanının boyutunu ayarlayabilirsiniz.",
    "zh-CN": "PDF Presenter 按文件夹和子文件夹组织演示。你可以搜索，通过菜单或拖动来移动演示，并在删除文件夹时选择保留演示副本。原有标签会转为文件夹，备注和视频不会丢失。在演讲者模式中可调整幻灯片预览和备注区域的大小。",
    "zh-TW": "PDF Presenter 以資料夾和子資料夾整理簡報。你可以搜尋，透過選單或拖曳移動簡報，並在刪除資料夾時選擇保留簡報副本。原有標籤會轉為資料夾，備註和影片不會遺失。在簡報者模式中可調整投影片預覽和備註區域的大小。",
    "ja": "PDF Presenterでプレゼンテーションをフォルダーとサブフォルダーに整理できます。検索、メニューやドラッグによる移動、フォルダー削除時のコピー保持を選べます。以前のタグはノートや動画を失わずにフォルダーに変換されます。発表者モードではスライドのプレビューとノート欄のサイズを調整できます。",
    "ko": "PDF Presenter는 발표 자료를 폴더와 하위 폴더로 정리합니다. 검색하거나 메뉴 또는 드래그로 이동하고, 폴더 삭제 시 사본을 보존할지 선택할 수 있습니다. 기존 태그는 노트와 동영상을 잃지 않고 폴더로 변환됩니다. 발표자 모드에서는 슬라이드 미리보기와 노트 영역의 크기를 조절할 수 있습니다."
  },
  {
    "category": "enhancement",
    "scope": "library",
    "es": "Los resúmenes de orientación de la Biblioteca se generan con el razonamiento desactivado para evitar el consumo adicional de los modelos que permiten apagarlo.",
    "en": "Library orientation summaries are generated with reasoning turned off to avoid extra usage on models that support disabling it.",
    "fr": "Les résumés d’orientation de la Bibliothèque sont générés sans raisonnement pour éviter une consommation supplémentaire avec les modèles qui permettent de le désactiver.",
    "de": "Orientierungszusammenfassungen der Bibliothek werden mit deaktiviertem Reasoning erstellt, um bei Modellen, die dies unterstützen, zusätzlichen Verbrauch zu vermeiden.",
    "pt": "Os resumos de orientação da Biblioteca são gerados com o raciocínio desativado para evitar consumo adicional nos modelos que permitem desligá-lo.",
    "pt-BR": "Os resumos de orientação da Biblioteca são gerados com o raciocínio desativado para evitar consumo adicional nos modelos que permitem desligá-lo.",
    "it": "I riassunti orientativi della Biblioteca vengono generati con il ragionamento disattivato per evitare consumi aggiuntivi nei modelli che consentono di disabilitarlo.",
    "tr": "Kütüphane yönlendirme özetleri, kapatmayı destekleyen modellerde ek kullanımı önlemek için akıl yürütme kapalı olarak oluşturulur.",
    "zh-CN": "资料库的导读摘要在关闭推理的情况下生成，以避免在支持关闭推理的模型上产生额外用量。",
    "zh-TW": "知識庫的導讀摘要在關閉推理的情況下產生，以避免在支援關閉推理的模型上產生額外用量。",
    "ja": "ライブラリの概要は推論をオフにして生成し、推論を無効にできるモデルでの追加使用量を抑えます。",
    "ko": "라이브러리의 안내 요약은 추론을 끈 상태로 생성하여, 추론 비활성화를 지원하는 모델에서 추가 사용량을 줄입니다."
  },
  {
    "category": "fix",
    "scope": "ai",
    "es": "Nodus vuelve a intentar una vez las respuestas interrumpidas por una pérdida de conexión antes de entregar texto. El Chat de investigación también repite una vez una respuesta que alcanza el límite de salida durante el razonamiento.",
    "en": "Nodus retries once when a response loses its connection before delivering text. Research Chat also retries once when a response reaches the output limit during reasoning.",
    "fr": "Nodus réessaie une fois lorsqu’une réponse perd la connexion avant de fournir du texte. Le Chat de recherche réessaie aussi une fois lorsqu’une réponse atteint la limite de sortie pendant le raisonnement.",
    "de": "Nodus versucht es einmal erneut, wenn eine Antwort vor der Textausgabe die Verbindung verliert. Der Recherche-Chat wiederholt auch einmal eine Antwort, die beim Reasoning das Ausgabelimit erreicht.",
    "pt": "O Nodus tenta novamente uma vez quando uma resposta perde a ligação antes de entregar texto. O Chat de investigação também repete uma vez uma resposta que atinge o limite de saída durante o raciocínio.",
    "pt-BR": "O Nodus tenta novamente uma vez quando uma resposta perde a conexão antes de entregar texto. O Chat de pesquisa também repete uma vez uma resposta que atinge o limite de saída durante o raciocínio.",
    "it": "Nodus riprova una volta quando una risposta perde la connessione prima di fornire testo. Anche la Chat di ricerca riprova una volta quando una risposta raggiunge il limite di output durante il ragionamento.",
    "tr": "Nodus, yanıt metin vermeden önce bağlantısını kaybederse bir kez yeniden dener. Araştırma Sohbeti de yanıt akıl yürütme sırasında çıktı sınırına ulaşırsa bir kez yeniden dener.",
    "zh-CN": "如果响应在输出文本前断开连接，Nodus 会重试一次。研究聊天也会在响应于推理阶段达到输出上限时重试一次。",
    "zh-TW": "如果回應在輸出文字前中斷連線，Nodus 會重試一次。研究聊天也會在回應於推理階段達到輸出上限時重試一次。",
    "ja": "応答がテキストを返す前に接続を失った場合、Nodusは1回再試行します。リサーチチャットも、推論中に出力上限に達した応答を1回再試行します。",
    "ko": "응답이 텍스트를 전달하기 전에 연결이 끊기면 Nodus가 한 번 재시도합니다. 연구 채팅도 응답이 추론 중 출력 한도에 도달하면 한 번 재시도합니다."
  },
  {
    "category": "fix",
    "scope": "academic",
    "es": "Inmersión puede consultar páginas de originales disponibles en Zotero e incluir citas que permiten abrirlas. El Chat de investigación distingue las fuentes locales de las consultas realizadas mediante Zotero MCP e informa cuando la conexión falla o no devuelve páginas legibles.",
    "en": "Immersion can read pages of originals available in Zotero and include citations that open them. Research Chat distinguishes local sources from actual Zotero MCP queries and reports connection failures or queries that return no readable pages.",
    "fr": "Immersion peut lire les pages des originaux disponibles dans Zotero et inclure des citations permettant de les ouvrir. Le Chat de recherche distingue les sources locales des requêtes Zotero MCP effectuées et signale les échecs de connexion ou l’absence de pages lisibles.",
    "de": "Immersion kann Seiten von in Zotero verfügbaren Originalen lesen und Zitate zum Öffnen dieser Seiten einfügen. Der Recherche-Chat unterscheidet lokale Quellen von tatsächlichen Zotero-MCP-Abfragen und meldet Verbindungsfehler oder Abfragen ohne lesbare Seiten.",
    "pt": "A Imersão pode consultar páginas de originais disponíveis no Zotero e incluir citações que permitem abri-las. O Chat de investigação distingue fontes locais de consultas efetivas ao Zotero MCP e indica falhas de ligação ou consultas sem páginas legíveis.",
    "pt-BR": "A Imersão pode consultar páginas de originais disponíveis no Zotero e incluir citações que permitem abri-las. O Chat de pesquisa distingue fontes locais de consultas efetivas ao Zotero MCP e informa falhas de conexão ou consultas sem páginas legíveis.",
    "it": "Immersione può leggere le pagine degli originali disponibili in Zotero e includere citazioni che le aprono. La Chat di ricerca distingue le fonti locali dalle effettive richieste a Zotero MCP e segnala errori di connessione o richieste senza pagine leggibili.",
    "tr": "Derin İnceleme, Zotero’da bulunan özgün belgelerin sayfalarını okuyabilir ve bu sayfaları açan atıflar ekleyebilir. Araştırma Sohbeti, yerel kaynakları gerçek Zotero MCP sorgularından ayırır ve bağlantı hatalarını veya okunabilir sayfa döndürmeyen sorguları bildirir.",
    "zh-CN": "沉浸阅读可查阅 Zotero 中原始文档的页面，并添加可打开这些页面的引用。研究聊天区分本地来源与实际执行的 Zotero MCP 查询，并报告连接失败或未返回可读页面的情况。",
    "zh-TW": "沉浸閱讀可查閱 Zotero 中原始文件的頁面，並加入可開啟這些頁面的引用。研究聊天區分本地來源與實際執行的 Zotero MCP 查詢，並回報連線失敗或未傳回可讀頁面的情況。",
    "ja": "没入では、Zoteroにある原資料のページを読み、ページを開ける引用を付けられます。リサーチチャットはローカルの資料と実際のZotero MCP照会を区別し、接続失敗や読めるページが返らない場合を報告します。",
    "ko": "몰입은 Zotero에 있는 원본 문서의 페이지를 읽고 해당 페이지를 여는 인용을 포함할 수 있습니다. 연구 채팅은 로컬 자료와 실제 Zotero MCP 조회를 구분하며, 연결 실패나 읽을 수 있는 페이지가 없는 조회를 알립니다."
  },
  {
    "category": "fix",
    "scope": "general",
    "es": "En los calendarios de Estudio y Docencia, el número del día ya no se superpone con los eventos en la vista mensual.",
    "en": "In Study and Teaching calendars, day numbers no longer overlap events in the month view.",
    "fr": "Dans les calendriers d’Étude et d’Enseignement, les numéros des jours ne chevauchent plus les événements dans la vue mensuelle.",
    "de": "In den Kalendern für Studium und Lehre überdecken die Tageszahlen in der Monatsansicht keine Termine mehr.",
    "pt": "Nos calendários de Estudo e Docência, o número do dia já não se sobrepõe aos eventos na vista mensal.",
    "pt-BR": "Nos calendários de Estudo e Ensino, o número do dia não se sobrepõe mais aos eventos na visualização mensal.",
    "it": "Nei calendari di Studio e Didattica, i numeri dei giorni non si sovrappongono più agli eventi nella vista mensile.",
    "tr": "Çalışma ve Öğretim takvimlerinin aylık görünümünde gün numaraları artık etkinliklerle üst üste gelmez.",
    "zh-CN": "学习和教学日历的月视图中，日期数字与事件分开显示，不再重叠，使当天的日期和事件都能清楚阅读。",
    "zh-TW": "學習和教學行事曆的月檢視中，日期數字與活動分開顯示，不再重疊，使當天的日期和活動都能清楚閱讀。",
    "ja": "学習と教育のカレンダーで、月表示の日付が予定に重ならなくなりました。",
    "ko": "학습 및 교육 달력의 월별 보기에서 날짜 숫자가 일정과 겹치지 않습니다."
  },
  {
    "category": "fix",
    "scope": "browser",
    "es": "El control de volumen en macOS sigue los cambios del sistema y conserva el último valor cuando lo ajustas rápidamente. Los controles del navegador identifican mejor el reproductor activo para pausar y reanudar lectores con audio personalizado.",
    "en": "The macOS volume control follows system changes and keeps the latest value when you adjust it rapidly. Browser controls identify the active player more accurately to pause and resume readers with custom audio.",
    "fr": "Le contrôle du volume sur macOS suit les changements du système et conserve la dernière valeur lors de réglages rapides. Les commandes du navigateur identifient mieux le lecteur actif pour mettre en pause et reprendre les lecteurs à audio personnalisé.",
    "de": "Die Lautstärkeregelung unter macOS folgt Systemänderungen und behält bei schnellen Anpassungen den letzten Wert. Browser-Steuerelemente erkennen den aktiven Player genauer, um Leseanwendungen mit eigener Audiowiedergabe anzuhalten und fortzusetzen.",
    "pt": "O controlo de volume no macOS acompanha as alterações do sistema e mantém o último valor quando o ajusta rapidamente. Os controlos do navegador identificam melhor o leitor ativo para pausar e retomar leitores com áudio personalizado.",
    "pt-BR": "O controle de volume no macOS acompanha as alterações do sistema e mantém o último valor quando você o ajusta rapidamente. Os controles do navegador identificam melhor o player ativo para pausar e retomar leitores com áudio personalizado.",
    "it": "Il controllo del volume su macOS segue le modifiche del sistema e conserva l’ultimo valore quando lo regoli rapidamente. I controlli del browser identificano meglio il lettore attivo per mettere in pausa e riprendere i lettori con audio personalizzato.",
    "tr": "macOS ses düzeyi kontrolü sistem değişikliklerini izler ve hızlı ayarlamalarda son değeri korur. Tarayıcı kontrolleri, özel ses kullanan okuyucuları duraklatıp sürdürmek için etkin oynatıcıyı daha doğru belirler.",
    "zh-CN": "macOS 音量控制会跟随系统变化，并在快速调整时保留最新值。浏览器控件能更准确地识别当前播放器，以暂停和继续使用自定义音频的阅读器。",
    "zh-TW": "macOS 音量控制會跟隨系統變化，並在快速調整時保留最新值。瀏覽器控制項能更準確地識別目前的播放器，以暫停和繼續使用自訂音訊的閱讀器。",
    "ja": "macOSの音量操作はシステムの変更を反映し、素早く調整しても最後に指定した値を保ちます。ブラウザーの操作部は再生中のプレイヤーをより正確に識別し、独自の音声再生を使うリーダーを一時停止・再開できます。",
    "ko": "macOS 음량 제어는 시스템 변경을 반영하고 빠르게 조절해도 마지막 값을 유지합니다. 브라우저 제어는 활성 플레이어를 더 정확하게 식별하여 자체 오디오를 사용하는 리더를 일시 정지하고 다시 재생합니다."
  },
  {
    "category": "fix",
    "scope": "library",
    "es": "El Índice documental espera a que termine la indexación de pasajes pendiente de la misma obra para evitar que se descarte su resultado. Mientras se prepara el texto, el progreso muestra «Preparando…» en lugar de «pasaje 1/0».",
    "en": "The Documentary Index waits for pending passage indexing of the same work to finish so its result is not discarded. While text is being prepared, progress shows “Preparing…” instead of “passage 1/0”.",
    "fr": "L’Index documentaire attend la fin de l’indexation des passages en attente pour la même œuvre afin que son résultat ne soit pas rejeté. Pendant la préparation du texte, la progression affiche « Préparation… » au lieu de « passage 1/0 ».",
    "de": "Der Dokumentindex wartet, bis die ausstehende Passageindexierung desselben Werks abgeschlossen ist, damit sein Ergebnis nicht verworfen wird. Während der Textvorbereitung zeigt der Fortschritt „Vorbereitung…“ statt „Passage 1/0“.",
    "pt": "O Índice documental aguarda o fim da indexação de passagens pendente da mesma obra para evitar que o resultado seja descartado. Durante a preparação do texto, o progresso mostra «A preparar…» em vez de «passagem 1/0».",
    "pt-BR": "O Índice documental aguarda o fim da indexação de passagens pendente da mesma obra para evitar que o resultado seja descartado. Durante a preparação do texto, o progresso mostra “Preparando…” em vez de “passagem 1/0”.",
    "it": "L’Indice documentale attende che l’indicizzazione dei passaggi in sospeso della stessa opera termini, evitando che il risultato venga scartato. Durante la preparazione del testo, l’avanzamento mostra «Preparazione…» anziché «passaggio 1/0».",
    "tr": "Belge Dizini, sonucunun atılmasını önlemek için aynı eserin bekleyen pasaj indekslemesinin tamamlanmasını bekler. Metin hazırlanırken ilerleme göstergesinde “pasaj 1/0” yerine “Hazırlanıyor…” görünür.",
    "zh-CN": "文献索引会等待同一作品的待处理段落索引完成，以免结果被丢弃。准备文本时，进度显示“准备中…”而非“段落 1/0”。",
    "zh-TW": "文獻索引會等待同一作品的待處理段落索引完成，以免結果被捨棄。準備文字時，進度顯示「準備中…」而非「段落 1/0」。",
    "ja": "文書索引は、同じ作品で待機中のパッセージ索引作成が完了するまで待ち、結果が破棄されるのを防ぎます。テキストの準備中は進捗に「パッセージ 1/0」ではなく「準備中…」と表示します。",
    "ko": "문서 색인은 결과가 폐기되지 않도록 같은 작품의 대기 중인 구절 색인 작업이 끝날 때까지 기다립니다. 텍스트 준비 중에는 진행 상태에 “구절 1/0” 대신 “준비 중…”이 표시됩니다."
  }
];
