// SPDX-FileCopyrightText: 2026 Jorge Pérez Burgueño and Nodus contributors
// SPDX-License-Identifier: AGPL-3.0-only
import type { CategorizedReleaseHighlight } from './releaseNotes';

/** Final user-visible changes since v5.7.4. First-release iterations are described together. */
export const RELEASE_5_8_0_HIGHLIGHTS: CategorizedReleaseHighlight[] = [
  {
    category: 'new', scope: 'toolkit',
    es: 'Nodus Scriptor, en Herramientas, permite escribir y organizar documentos con texto enriquecido, tablas, imágenes y fórmulas. Inserta fuentes e ideas con [[, añade citas, bibliografía y notas, reúne capítulos y exporta a Word, PDF o LaTeX. Incluye historial de versiones, escritura a pantalla completa y mejoras de texto con IA que puedes cancelar o deshacer. Disponible en escritorio y en la web del servidor.',
    en: 'Nodus Scriptor, in Tools, lets you write and organize documents with rich text, tables, images and formulas. Insert sources and ideas with [[, add citations, bibliographies and notes, assemble chapters and export to Word, PDF or LaTeX. It includes version history, fullscreen writing and AI text improvements that you can cancel or undo. Available on Desktop and Server web.',
    fr: 'Nodus Scriptor, dans Outils, permet de rédiger et d’organiser des documents avec du texte enrichi, des tableaux, des images et des formules. Insérez des sources et des idées avec [[, ajoutez citations, bibliographie et notes, assemblez des chapitres et exportez vers Word, PDF ou LaTeX. Il comprend un historique des versions, la rédaction en plein écran et des améliorations du texte par IA que vous pouvez interrompre ou annuler. Disponible sur ordinateur et sur le web du serveur.',
    de: 'Mit Nodus Scriptor unter Werkzeuge schreiben und organisieren Sie Dokumente mit formatiertem Text, Tabellen, Bildern und Formeln. Fügen Sie Quellen und Ideen mit [[ ein, ergänzen Sie Zitate, Literaturverzeichnisse und Anmerkungen, stellen Sie Kapitel zusammen und exportieren Sie nach Word, PDF oder LaTeX. Enthalten sind Versionsverlauf, Schreiben im Vollbild und KI-Textverbesserungen, die Sie abbrechen oder rückgängig machen können. Verfügbar auf dem Desktop und im Server-Webzugang.',
    pt: 'O Nodus Scriptor, em Ferramentas, permite escrever e organizar documentos com texto formatado, tabelas, imagens e fórmulas. Insira fontes e ideias com [[, acrescente citações, bibliografia e notas, reúna capítulos e exporte para Word, PDF ou LaTeX. Inclui histórico de versões, escrita em ecrã inteiro e melhorias de texto com IA que pode cancelar ou desfazer. Disponível no computador e na web do servidor.',
    'pt-BR': 'O Nodus Scriptor, em Ferramentas, permite escrever e organizar documentos com texto formatado, tabelas, imagens e fórmulas. Insira fontes e ideias com [[, adicione citações, bibliografia e notas, reúna capítulos e exporte para Word, PDF ou LaTeX. Inclui histórico de versões, escrita em tela cheia e melhorias de texto com IA que você pode cancelar ou desfazer. Disponível no desktop e na web do servidor.',
    it: 'Nodus Scriptor, in Strumenti, permette di scrivere e organizzare documenti con testo formattato, tabelle, immagini e formule. Inserisci fonti e idee con [[, aggiungi citazioni, bibliografie e note, riunisci capitoli ed esporta in Word, PDF o LaTeX. Include cronologia delle versioni, scrittura a schermo intero e miglioramenti del testo con IA che puoi interrompere o annullare. Disponibile sul desktop e sul web del server.',
    tr: 'Araçlar içindeki Nodus Scriptor, biçimlendirilmiş metin, tablo, görsel ve formüllerle belge yazmanızı ve düzenlemenizi sağlar. [[ ile kaynak ve fikir ekleyebilir, atıf, kaynakça ve not oluşturabilir, bölümleri birleştirip Word, PDF veya LaTeX olarak dışa aktarabilirsiniz. Sürüm geçmişi, tam ekran yazma ve iptal edebileceğiniz veya geri alabileceğiniz yapay zekâ metin iyileştirmeleri içerir. Masaüstünde ve sunucunun web arayüzünde kullanılabilir.',
    'zh-CN': '工具中的 Nodus Scriptor 可编写和整理包含富文本、表格、图片和公式的文档。输入 [[ 可插入来源和观点，还可添加引文、参考文献和注释，组合章节并导出为 Word、PDF 或 LaTeX。支持版本历史、全屏写作，以及可取消或撤销的 AI 文本修改。桌面端和服务器网页端均可使用。',
    'zh-TW': '工具中的 Nodus Scriptor 可撰寫和整理包含格式化文字、表格、圖片和公式的文件。輸入 [[ 可插入來源和觀點，亦可加入引文、參考文獻和註釋，組合章節並匯出為 Word、PDF 或 LaTeX。支援版本歷程、全螢幕寫作，以及可取消或復原的 AI 文字修改。桌面版和伺服器網頁版均可使用。',
    ja: 'ツールのNodus Scriptorで、書式付きテキスト、表、画像、数式を含む文書を作成して整理できます。[[ で資料やアイデアを挿入し、引用、参考文献、注を追加し、章をまとめてWord、PDF、LaTeXに書き出せます。バージョン履歴、全画面での執筆、中止や取り消しができるAIの文章改善も使えます。デスクトップとサーバーのWeb画面で利用できます。',
    ko: '도구의 Nodus Scriptor에서 서식 있는 텍스트, 표, 이미지, 수식으로 문서를 작성하고 정리할 수 있습니다. [[ 로 자료와 아이디어를 삽입하고, 인용, 참고문헌, 주석을 추가하며, 장을 모아 Word, PDF 또는 LaTeX로 내보낼 수 있습니다. 버전 기록, 전체 화면 작성, 취소하거나 되돌릴 수 있는 AI 텍스트 개선을 제공합니다. 데스크톱과 서버 웹에서 사용할 수 있습니다.',
  },
  {
    category: 'enhancement', scope: 'toolkit',
    es: 'Nodus Focus está disponible en Herramientas para las nueve bóvedas. Cambiar de bóveda no interrumpe el temporizador. La navegación se adapta a cada bóveda y el historial común registra el tiempo dedicado a cada una. Conserva los historiales anteriores y permite personalizar los accesos de cada bóveda.',
    en: 'Nodus Focus is available in Tools for all nine vaults. Switching vaults does not interrupt the timer. Navigation adapts to each vault and the shared history records time spent in each one. Previous histories are retained and each vault’s shortcuts can be customized.',
    fr: 'Nodus Focus est disponible dans Outils pour les neuf coffres. Changer de coffre n’interrompt pas le minuteur. La navigation s’adapte à chaque coffre et l’historique commun enregistre le temps consacré à chacun. Les anciens historiques sont conservés et les raccourcis de chaque coffre sont personnalisables.',
    de: 'Nodus Focus steht unter Werkzeuge für alle neun Tresore bereit. Beim Wechsel des Tresors läuft der Timer weiter. Die Navigation passt sich an jeden Tresor an und der gemeinsame Verlauf erfasst die jeweilige Arbeitszeit. Bisherige Verläufe bleiben erhalten und die Verknüpfungen lassen sich pro Tresor anpassen.',
    pt: 'O Nodus Focus está disponível em Ferramentas para os nove cofres. Mudar de cofre não interrompe o temporizador. A navegação adapta-se a cada cofre e o histórico comum regista o tempo dedicado a cada um. Os históricos anteriores são preservados e pode personalizar os atalhos de cada cofre.',
    'pt-BR': 'O Nodus Focus está disponível em Ferramentas para os nove cofres. Trocar de cofre não interrompe o temporizador. A navegação se adapta a cada cofre e o histórico compartilhado registra o tempo dedicado a cada um. Os históricos anteriores são preservados e os atalhos de cada cofre podem ser personalizados.',
    it: 'Nodus Focus è disponibile in Strumenti per tutti i nove depositi. Cambiare deposito non interrompe il timer. La navigazione si adatta a ciascun deposito e la cronologia comune registra il tempo dedicato a ognuno. Le cronologie precedenti vengono conservate e le scorciatoie si possono personalizzare per deposito.',
    tr: 'Nodus Focus, dokuz kasanın tamamı için Araçlar içinde kullanılabilir. Kasa değiştirmek zamanlayıcıyı durdurmaz. Gezinme her kasaya uyarlanır ve ortak geçmiş her kasada geçirilen süreyi kaydeder. Önceki geçmişler korunur ve her kasanın kısayolları özelleştirilebilir.',
    'zh-CN': 'Nodus Focus 可在全部九类知识库的工具中使用。切换知识库不会中断计时器。导航随知识库调整，共享历史分别记录各知识库的工作时间。保留已有历史，并可为每个知识库自定义快捷入口。',
    'zh-TW': 'Nodus Focus 可在全部九類知識庫的工具中使用。切換知識庫不會中斷計時器。導覽隨知識庫調整，共用歷程分別記錄各知識庫的工作時間。保留既有歷程，並可為每個知識庫自訂快捷入口。',
    ja: 'Nodus Focusは9種類すべての保管庫のツールで利用できます。保管庫を切り替えてもタイマーは止まりません。ナビゲーションは各保管庫に合わせて変わり、共通の履歴に保管庫ごとの作業時間を記録します。以前の履歴を保持し、各保管庫のショートカットを設定できます。',
    ko: 'Nodus Focus를 아홉 가지 보관함 모두의 도구에서 사용할 수 있습니다. 보관함을 바꿔도 타이머가 중단되지 않습니다. 탐색 메뉴는 보관함에 맞게 바뀌며 공통 기록에 보관함별 작업 시간을 저장합니다. 이전 기록을 보존하고 보관함별 바로가기를 설정할 수 있습니다.',
  },
  {
    category: 'enhancement', scope: 'toolkit',
    es: 'PDF Presenter añade en macOS una conexión nativa alternativa para la app móvil. Se activa al iniciar Nodus con NODUS_PRESENTER_TRANSPORT=multipeer. Con esta conexión, el puntero, el resaltado y el dibujo responden con mayor rapidez.',
    en: 'PDF Presenter adds an alternative native connection for the mobile app on macOS. Enable it by starting Nodus with NODUS_PRESENTER_TRANSPORT=multipeer. This connection improves the responsiveness of the pointer, highlighting and drawing.',
    fr: 'PDF Presenter ajoute une connexion native alternative pour l’app mobile sur macOS. Activez-la en démarrant Nodus avec NODUS_PRESENTER_TRANSPORT=multipeer. Cette connexion améliore la réactivité du pointeur, de la mise en évidence et du dessin.',
    de: 'PDF Presenter bietet unter macOS eine alternative native Verbindung zur mobilen App. Starten Sie Nodus mit NODUS_PRESENTER_TRANSPORT=multipeer, um sie zu aktivieren. Damit reagieren Zeiger, Hervorhebung und Zeichnen schneller.',
    pt: 'O PDF Presenter acrescenta no macOS uma ligação nativa alternativa para a aplicação móvel. Ative-a ao iniciar o Nodus com NODUS_PRESENTER_TRANSPORT=multipeer. Esta ligação melhora a resposta do ponteiro, do realce e do desenho.',
    'pt-BR': 'O PDF Presenter adiciona no macOS uma conexão nativa alternativa para o app móvel. Ative-a ao iniciar o Nodus com NODUS_PRESENTER_TRANSPORT=multipeer. Essa conexão melhora a resposta do ponteiro, do destaque e do desenho.',
    it: 'PDF Presenter aggiunge su macOS una connessione nativa alternativa per l’app mobile. Attivala avviando Nodus con NODUS_PRESENTER_TRANSPORT=multipeer. Questa connessione migliora la risposta del puntatore, dell’evidenziazione e del disegno.',
    tr: 'PDF Presenter, macOS üzerinde mobil uygulama için alternatif bir yerel bağlantı ekler. Nodus’u NODUS_PRESENTER_TRANSPORT=multipeer ile başlatarak etkinleştirin. Bu bağlantı işaretçi, vurgulama ve çizimin daha hızlı yanıt vermesini sağlar.',
    'zh-CN': 'PDF Presenter 在 macOS 上为移动应用增加了另一种原生连接。启动 Nodus 时设置 NODUS_PRESENTER_TRANSPORT=multipeer 即可启用。此连接提高了指针、高亮和绘图的响应速度。',
    'zh-TW': 'PDF Presenter 在 macOS 上為行動 App 增加了另一種原生連線。啟動 Nodus 時設定 NODUS_PRESENTER_TRANSPORT=multipeer 即可啟用。此連線提高了指標、醒目提示和繪圖的反應速度。',
    ja: 'PDF PresenterはmacOSでモバイルアプリとの別のネイティブ接続を利用できます。NODUS_PRESENTER_TRANSPORT=multipeer を設定してNodusを起動すると有効になります。この接続ではポインター、強調表示、描画の反応が速くなります。',
    ko: 'PDF Presenter가 macOS에서 모바일 앱용 대체 네이티브 연결을 제공합니다. NODUS_PRESENTER_TRANSPORT=multipeer를 설정하여 Nodus를 시작하면 활성화됩니다. 이 연결은 포인터, 강조 표시, 그리기의 반응 속도를 개선합니다.',
  },
  {
    category: 'enhancement', scope: 'ai',
    es: 'Las consultas de síntesis con Chemistry Studio pueden usar condiciones de reacciones documentadas, esquemas de tus libros y listas comerciales importadas por ti. El informe muestra fuentes por paso, disponibilidad de materiales y posibles incompatibilidades entre reactivos y grupos funcionales. La búsqueda de rutas también considera los reactivos de los esquemas. Requiere Chemistry Studio 2.5.8 y los índices o listas locales correspondientes.',
    en: 'Synthesis queries with Chemistry Studio can use recorded reaction conditions, schemes from your books and commercial stock lists you import. The report shows sources for each step, material availability and possible incompatibilities between reagents and functional groups. Route search also considers reagents in the schemes. Requires Chemistry Studio 2.5.8 and the corresponding local indexes or lists.',
    fr: 'Les questions de synthèse avec Chemistry Studio peuvent utiliser des conditions réactionnelles documentées, les schémas de vos livres et les listes commerciales que vous importez. Le rapport indique les sources de chaque étape, la disponibilité des produits et les incompatibilités possibles entre réactifs et groupes fonctionnels. La recherche de voies tient aussi compte des réactifs des schémas. Nécessite Chemistry Studio 2.5.8 et les index ou listes locaux correspondants.',
    de: 'Syntheseanfragen mit Chemistry Studio können dokumentierte Reaktionsbedingungen, Schemata aus Ihren Büchern und selbst importierte kommerzielle Bestandslisten nutzen. Der Bericht zeigt Quellen pro Schritt, Materialverfügbarkeit und mögliche Unverträglichkeiten zwischen Reagenzien und funktionellen Gruppen. Die Routensuche berücksichtigt auch Reagenzien aus den Schemata. Erfordert Chemistry Studio 2.5.8 und die entsprechenden lokalen Indizes oder Listen.',
    pt: 'As consultas de síntese com o Chemistry Studio podem usar condições de reações documentadas, esquemas dos seus livros e listas comerciais importadas por si. O relatório mostra fontes por etapa, disponibilidade de materiais e possíveis incompatibilidades entre reagentes e grupos funcionais. A pesquisa de rotas também considera os reagentes dos esquemas. Requer Chemistry Studio 2.5.8 e os índices ou listas locais correspondentes.',
    'pt-BR': 'As consultas de síntese com o Chemistry Studio podem usar condições de reações documentadas, esquemas dos seus livros e listas comerciais que você importa. O relatório mostra fontes por etapa, disponibilidade de materiais e possíveis incompatibilidades entre reagentes e grupos funcionais. A busca de rotas também considera os reagentes dos esquemas. Requer Chemistry Studio 2.5.8 e os índices ou listas locais correspondentes.',
    it: 'Le domande di sintesi con Chemistry Studio possono usare condizioni di reazioni documentate, schemi dei tuoi libri e liste commerciali che importi. Il rapporto mostra fonti per ogni passaggio, disponibilità dei materiali e possibili incompatibilità tra reagenti e gruppi funzionali. La ricerca dei percorsi considera anche i reagenti degli schemi. Richiede Chemistry Studio 2.5.8 e i relativi indici o elenchi locali.',
    tr: 'Chemistry Studio ile sentez sorguları, kayıtlı tepkime koşullarını, kitaplarınızdaki şemaları ve içe aktardığınız ticari stok listelerini kullanabilir. Rapor her adımın kaynaklarını, malzeme bulunabilirliğini ve reaktiflerle fonksiyonel gruplar arasındaki olası uyumsuzlukları gösterir. Rota araması şemalardaki reaktifleri de dikkate alır. Chemistry Studio 2.5.8 ve ilgili yerel indeksler veya listeler gerekir.',
    'zh-CN': 'Chemistry Studio 的合成查询可使用已记录的反应条件、你书中的反应示意图，以及你导入的商业库存清单。报告按步骤列出来源、材料供应情况，以及试剂与官能团之间的潜在不相容性。路线搜索也会考虑示意图中的试剂。需要 Chemistry Studio 2.5.8 及相应的本地索引或清单。',
    'zh-TW': 'Chemistry Studio 的合成查詢可使用已記錄的反應條件、你書中的反應示意圖，以及你匯入的商業庫存清單。報告逐步列出來源、材料供應情況，以及試劑與官能基之間的潛在不相容性。路線搜尋亦會考慮示意圖中的試劑。需要 Chemistry Studio 2.5.8 及相應的本機索引或清單。',
    ja: 'Chemistry Studioの合成に関する質問では、記録された反応条件、自分の書籍の反応図、取り込んだ市販品の在庫リストを利用できます。レポートは各工程の出典、材料の入手状況、試薬と官能基の不適合の可能性を示します。経路検索では反応図の試薬も考慮します。Chemistry Studio 2.5.8と対応するローカル索引またはリストが必要です。',
    ko: 'Chemistry Studio의 합성 질문에서 기록된 반응 조건, 자신의 책에 있는 반응 도식, 직접 가져온 상업용 재고 목록을 활용할 수 있습니다. 보고서는 단계별 출처, 재료 공급 여부, 시약과 작용기 간의 잠재적 비호환성을 보여 줍니다. 경로 검색도 도식의 시약을 고려합니다. Chemistry Studio 2.5.8과 해당 로컬 색인 또는 목록이 필요합니다.',
  },
  {
    category: 'enhancement', scope: 'academic',
    es: 'La búsqueda de ideas en Research Chat es más rápida cuando seleccionas muchas obras. Mantiene los mismos límites del corpus seleccionado y evita revisar cada obra por separado para cada idea.',
    en: 'Idea search in Research Chat is faster when you select many works. It keeps the same selected-corpus boundaries and avoids checking every work separately for each idea.',
    fr: 'La recherche d’idées dans Research Chat est plus rapide lorsque vous sélectionnez de nombreuses œuvres. Elle conserve les limites du corpus choisi et évite de vérifier chaque œuvre séparément pour chaque idée.',
    de: 'Die Ideensuche in Research Chat ist bei vielen ausgewählten Werken schneller. Die Grenzen des ausgewählten Korpus bleiben erhalten, ohne jedes Werk für jede Idee einzeln zu prüfen.',
    pt: 'A pesquisa de ideias no Research Chat é mais rápida quando seleciona muitas obras. Mantém os limites do corpus selecionado e evita verificar cada obra separadamente para cada ideia.',
    'pt-BR': 'A busca de ideias no Research Chat fica mais rápida quando você seleciona muitas obras. Mantém os limites do corpus selecionado e evita verificar cada obra separadamente para cada ideia.',
    it: 'La ricerca di idee in Research Chat è più rapida quando selezioni molte opere. Mantiene i limiti del corpus selezionato ed evita di verificare ogni opera separatamente per ogni idea.',
    tr: 'Research Chat’te çok sayıda eser seçildiğinde fikir araması daha hızlıdır. Seçilen külliyatın sınırlarını korur ve her fikir için bütün eserleri ayrı ayrı kontrol etmekten kaçınır.',
    'zh-CN': '在 Research Chat 中选择大量作品时，观点搜索更快。仍严格限定在所选语料范围内，无需为每个观点逐一检查全部作品。',
    'zh-TW': '在 Research Chat 中選取大量作品時，觀點搜尋更快。仍嚴格限定在所選語料範圍內，無須為每個觀點逐一檢查全部作品。',
    ja: 'Research Chatで多数の作品を選択した際のアイデア検索が速くなりました。選択した資料の範囲を守りながら、アイデアごとに全作品を個別確認する処理を減らします。',
    ko: 'Research Chat에서 많은 자료를 선택했을 때 아이디어 검색이 빨라졌습니다. 선택한 자료 범위를 유지하면서 아이디어마다 모든 자료를 따로 확인하는 작업을 줄입니다.',
  },
  {
    category: 'enhancement', scope: 'general',
    es: 'La AppImage de Linux permite actualizar Nodus con herramientas externas AppImageUpdate. La release incluye los datos necesarios y un archivo .zsync. La actualización integrada y los enlaces de descarga anteriores siguen disponibles.',
    en: 'The Linux AppImage supports updating Nodus with external AppImageUpdate tools. The release includes the required metadata and a .zsync file. The built-in updater and previous download links remain available.',
    fr: 'L’AppImage Linux permet de mettre Nodus à jour avec des outils externes AppImageUpdate. La version inclut les métadonnées nécessaires et un fichier .zsync. La mise à jour intégrée et les anciens liens de téléchargement restent disponibles.',
    de: 'Das Linux-AppImage unterstützt Nodus-Updates mit externen AppImageUpdate-Werkzeugen. Die Veröffentlichung enthält die erforderlichen Metadaten und eine .zsync-Datei. Die integrierte Aktualisierung und bisherige Downloadlinks bleiben verfügbar.',
    pt: 'A AppImage de Linux permite atualizar o Nodus com ferramentas externas AppImageUpdate. A versão inclui os metadados necessários e um ficheiro .zsync. A atualização integrada e os links de transferência anteriores continuam disponíveis.',
    'pt-BR': 'A AppImage do Linux permite atualizar o Nodus com ferramentas externas AppImageUpdate. A versão inclui os metadados necessários e um arquivo .zsync. A atualização integrada e os links de download anteriores continuam disponíveis.',
    it: 'L’AppImage per Linux consente di aggiornare Nodus con strumenti esterni AppImageUpdate. La versione include i metadati necessari e un file .zsync. Restano disponibili l’aggiornamento integrato e i precedenti link di download.',
    tr: 'Linux AppImage, harici AppImageUpdate araçlarıyla Nodus’u güncellemeyi destekler. Sürüm gerekli üst verileri ve bir .zsync dosyasını içerir. Yerleşik güncelleyici ve önceki indirme bağlantıları kullanılmaya devam eder.',
    'zh-CN': 'Linux AppImage 支持通过外部 AppImageUpdate 工具更新 Nodus。此版本包含所需元数据和 .zsync 文件。内置更新功能及原有下载链接仍可使用。',
    'zh-TW': 'Linux AppImage 支援透過外部 AppImageUpdate 工具更新 Nodus。此版本包含所需中繼資料和 .zsync 檔案。內建更新功能及原有下載連結仍可使用。',
    ja: 'LinuxのAppImageは、外部のAppImageUpdateツールによるNodusの更新に対応しました。必要なメタデータと.zsyncファイルを含みます。内蔵の更新機能と以前のダウンロードリンクも引き続き使えます。',
    ko: 'Linux AppImage는 외부 AppImageUpdate 도구로 Nodus를 업데이트할 수 있습니다. 필요한 메타데이터와 .zsync 파일이 포함됩니다. 내장 업데이트 기능과 기존 다운로드 링크도 계속 사용할 수 있습니다.',
  },
  {
    category: 'fix', scope: 'toolkit',
    es: 'Los nombres largos de las presentaciones ya no ensanchan la barra lateral de PDF Presenter ni ocultan el botón de opciones. Las tarjetas se ajustan al ancho disponible y permiten desplazarse verticalmente.',
    en: 'Long presentation names no longer widen the PDF Presenter sidebar or hide the options button. Cards fit the available width and retain vertical scrolling.',
    fr: 'Les longs noms de présentations n’élargissent plus la barre latérale de PDF Presenter et ne masquent plus le bouton d’options. Les cartes respectent la largeur disponible et conservent le défilement vertical.',
    de: 'Lange Präsentationsnamen verbreitern die PDF-Presenter-Seitenleiste nicht mehr und verdecken nicht mehr die Optionsschaltfläche. Karten passen in die verfügbare Breite und bleiben vertikal scrollbar.',
    pt: 'Os nomes longos das apresentações já não alargam a barra lateral do PDF Presenter nem ocultam o botão de opções. Os cartões ajustam-se à largura disponível e mantêm o deslocamento vertical.',
    'pt-BR': 'Nomes longos de apresentações não alargam mais a barra lateral do PDF Presenter nem ocultam o botão de opções. Os cartões se ajustam à largura disponível e mantêm a rolagem vertical.',
    it: 'I nomi lunghi delle presentazioni non allargano più la barra laterale di PDF Presenter e non nascondono il pulsante delle opzioni. Le schede rispettano la larghezza disponibile e mantengono lo scorrimento verticale.',
    tr: 'Uzun sunum adları artık PDF Presenter kenar çubuğunu genişletmez veya seçenek düğmesini gizlemez. Kartlar kullanılabilir genişliğe sığar ve dikey kaydırma korunur.',
    'zh-CN': '较长的演示名称不再撑宽 PDF Presenter 侧栏或遮住选项按钮。卡片适应可用宽度，并保留垂直滚动。',
    'zh-TW': '較長的簡報名稱不再撐寬 PDF Presenter 側欄或遮住選項按鈕。卡片配合可用寬度，並保留垂直捲動。',
    ja: '長いプレゼンテーション名でPDF Presenterのサイドバーが広がったり、オプションボタンが隠れたりしなくなりました。カードは表示幅に収まり、縦方向にスクロールできます。',
    ko: '긴 발표 이름이 PDF Presenter 사이드바를 넓히거나 옵션 버튼을 가리지 않습니다. 카드는 사용 가능한 너비에 맞춰지며 세로 스크롤을 유지합니다.',
  },
  {
    category: 'fix', scope: 'browser',
    es: 'El navegador conserva visible la página al abrir menús y diálogos. Al cambiar el ancho de la barra lateral, la página se ajusta sin superponerse a la navegación.',
    en: 'The browser keeps the page visible when you open menus and dialogs. When you resize the sidebar, the page adjusts without overlapping navigation.',
    fr: 'Le navigateur garde la page visible lorsque vous ouvrez des menus et des dialogues. Quand vous redimensionnez la barre latérale, la page s’ajuste sans chevaucher la navigation.',
    de: 'Der Browser zeigt die Seite auch beim Öffnen von Menüs und Dialogen an. Beim Ändern der Seitenleistenbreite passt sich die Seite an, ohne die Navigation zu überdecken.',
    pt: 'O navegador mantém a página visível ao abrir menus e diálogos. Ao alterar a largura da barra lateral, a página ajusta-se sem se sobrepor à navegação.',
    'pt-BR': 'O navegador mantém a página visível ao abrir menus e diálogos. Ao alterar a largura da barra lateral, a página se ajusta sem se sobrepor à navegação.',
    it: 'Il browser mantiene visibile la pagina quando apri menu e finestre di dialogo. Ridimensionando la barra laterale, la pagina si adatta senza sovrapporsi alla navigazione.',
    tr: 'Tarayıcı, menüler ve iletişim kutuları açılırken sayfayı görünür tutar. Kenar çubuğunun genişliği değiştirildiğinde sayfa gezinme alanının üzerine gelmeden uyarlanır.',
    'zh-CN': '打开菜单和对话框时，浏览器页面保持可见。调整侧栏宽度时，页面随之调整，不再覆盖导航区域。',
    'zh-TW': '開啟選單和對話框時，瀏覽器頁面保持可見。調整側欄寬度時，頁面隨之調整，不再覆蓋導覽區域。',
    ja: 'メニューやダイアログを開いても、ブラウザーのページ表示が保たれます。サイドバーの幅を変更すると、ページがナビゲーションに重ならずに調整されます。',
    ko: '메뉴와 대화상자를 열어도 브라우저 페이지가 계속 표시됩니다. 사이드바 너비를 바꾸면 페이지가 탐색 영역과 겹치지 않도록 조정됩니다.',
  },
  {
    category: 'fix', scope: 'library',
    es: 'La extracción de PDF y la recuperación de fuentes ya no pierden un resultado terminado cuando su proceso en segundo plano se cierra. Research Chat puede recibirlo también mientras se ejecutan otras tareas intensivas.',
    en: 'PDF extraction and source retrieval no longer lose a completed result when their background process exits. Research Chat can receive it while other intensive tasks are running.',
    fr: 'L’extraction de PDF et la recherche de sources ne perdent plus un résultat terminé quand leur processus en arrière-plan se ferme. Research Chat peut le recevoir même pendant d’autres tâches intensives.',
    de: 'PDF-Extraktion und Quellenabruf verlieren fertige Ergebnisse nicht mehr, wenn ihr Hintergrundprozess endet. Research Chat kann sie auch während anderer rechenintensiver Aufgaben erhalten.',
    pt: 'A extração de PDF e a recuperação de fontes já não perdem um resultado concluído quando o processo em segundo plano termina. O Research Chat pode recebê-lo mesmo durante outras tarefas intensivas.',
    'pt-BR': 'A extração de PDF e a recuperação de fontes não perdem mais um resultado concluído quando o processo em segundo plano termina. O Research Chat pode recebê-lo mesmo durante outras tarefas intensivas.',
    it: 'L’estrazione dei PDF e il recupero delle fonti non perdono più un risultato completato quando il processo in background termina. Research Chat può riceverlo anche durante altre attività intensive.',
    tr: 'PDF çıkarma ve kaynak getirme işlemleri, arka plan süreci sona erdiğinde tamamlanan sonuçları artık kaybetmez. Research Chat, diğer yoğun işlemler sürerken de bu sonuçları alabilir.',
    'zh-CN': 'PDF 提取和来源检索不会再因后台进程退出而丢失已完成的结果。即使同时运行其他高负载任务，Research Chat 也能接收这些结果。',
    'zh-TW': 'PDF 擷取和來源檢索不會再因背景處理程序結束而遺失已完成的結果。即使同時執行其他高負載工作，Research Chat 亦能接收這些結果。',
    ja: 'PDF抽出や資料検索のバックグラウンド処理が終了しても、完了した結果が失われなくなりました。他の負荷の高い処理が実行中でもResearch Chatは結果を受け取れます。',
    ko: 'PDF 추출과 자료 검색의 백그라운드 프로세스가 종료되어도 완료된 결과가 사라지지 않습니다. 다른 고부하 작업이 실행 중이어도 Research Chat이 결과를 받을 수 있습니다.',
  },
  {
    category: 'fix', scope: 'ai',
    es: 'Desactivar el razonamiento ya no provoca errores con modelos que requieren un ajuste específico. Nodus usa el ajuste admitido para desactivarlo o el nivel mínimo permitido si es obligatorio. Conserva el nivel que hayas elegido cuando el razonamiento está activado.',
    en: 'Turning reasoning off no longer causes errors with models that require a specific setting. Nodus uses the supported opt-out or the lowest permitted level when reasoning is mandatory. It preserves your chosen level when reasoning is enabled.',
    fr: 'Désactiver le raisonnement ne provoque plus d’erreurs avec les modèles nécessitant un réglage particulier. Nodus utilise le réglage de désactivation accepté ou le niveau minimal autorisé si le raisonnement est obligatoire. Le niveau choisi est conservé lorsque le raisonnement est activé.',
    de: 'Das Ausschalten des Reasonings verursacht bei Modellen mit besonderen Einstellungen keine Fehler mehr. Nodus nutzt die unterstützte Deaktivierung oder bei verpflichtendem Reasoning die niedrigste zulässige Stufe. Bei aktiviertem Reasoning bleibt die von Ihnen gewählte Stufe erhalten.',
    pt: 'Desativar o raciocínio já não provoca erros nos modelos que exigem uma definição específica. O Nodus usa a opção de desativação suportada ou o nível mínimo permitido quando o raciocínio é obrigatório. Mantém o nível escolhido quando o raciocínio está ativo.',
    'pt-BR': 'Desativar o raciocínio não provoca mais erros nos modelos que exigem uma configuração específica. O Nodus usa a opção de desativação aceita ou o nível mínimo permitido quando o raciocínio é obrigatório. Mantém o nível escolhido quando o raciocínio está ativado.',
    it: 'Disattivare il ragionamento non causa più errori con i modelli che richiedono un’impostazione specifica. Nodus usa l’opzione di disattivazione supportata o il livello minimo consentito quando il ragionamento è obbligatorio. Mantiene il livello scelto quando il ragionamento è attivo.',
    tr: 'Akıl yürütmeyi kapatmak, özel ayar gerektiren modellerde artık hataya yol açmaz. Nodus desteklenen kapatma ayarını veya akıl yürütme zorunluysa izin verilen en düşük düzeyi kullanır. Akıl yürütme açıkken seçtiğiniz düzeyi korur.',
    'zh-CN': '对于需要特定设置的模型，关闭推理不再导致错误。Nodus 使用模型支持的关闭设置，如果推理是强制的，则使用允许的最低级别。启用推理时会保留你选择的级别。',
    'zh-TW': '對於需要特定設定的模型，關閉推理不再造成錯誤。Nodus 使用模型支援的關閉設定，若推理為強制要求，則使用允許的最低層級。啟用推理時會保留你選擇的層級。',
    ja: '特別な設定が必要なモデルでも、推論をオフにした際のエラーを防ぎます。Nodusは対応する無効化設定を使い、推論が必須の場合は許容される最低レベルを選びます。推論がオンの場合は選択したレベルを保持します。',
    ko: '특정 설정이 필요한 모델에서 추론을 꺼도 오류가 발생하지 않습니다. Nodus는 지원되는 비활성화 설정을 사용하고, 추론이 필수이면 허용되는 최소 수준을 선택합니다. 추론이 켜져 있으면 사용자가 선택한 수준을 유지합니다.',
  },
  {
    category: 'fix', scope: 'general',
    es: 'El estado de actualización se muestra una sola vez en el aviso bajo la cabecera. El aviso permanece visible durante la copia de seguridad y la instalación, también cuando instalas desde Ajustes una actualización que habías pospuesto.',
    en: 'Update status appears once in the banner below the header. The banner stays visible during backup and installation, including when you install a postponed update from Settings.',
    fr: 'L’état de la mise à jour apparaît une seule fois dans le bandeau sous l’en-tête. Le bandeau reste visible pendant la sauvegarde et l’installation, y compris lorsque vous installez depuis Réglages une mise à jour reportée.',
    de: 'Der Aktualisierungsstatus erscheint einmal im Hinweis unter der Kopfzeile. Dieser bleibt während Sicherung und Installation sichtbar, auch wenn Sie eine verschobene Aktualisierung über Einstellungen installieren.',
    pt: 'O estado da atualização aparece uma única vez no aviso abaixo do cabeçalho. O aviso permanece visível durante a cópia de segurança e a instalação, incluindo quando instala em Definições uma atualização que tinha adiado.',
    'pt-BR': 'O status da atualização aparece uma única vez no aviso abaixo do cabeçalho. O aviso permanece visível durante o backup e a instalação, inclusive quando você instala em Configurações uma atualização que havia adiado.',
    it: 'Lo stato dell’aggiornamento appare una sola volta nell’avviso sotto l’intestazione. L’avviso resta visibile durante il backup e l’installazione, anche quando installi da Impostazioni un aggiornamento rimandato.',
    tr: 'Güncelleme durumu başlığın altındaki bildirimde bir kez gösterilir. Bildirim yedekleme ve kurulum sırasında görünür kalır. Ayarlar’dan ertelenmiş bir güncelleme yüklendiğinde de görünmeye devam eder.',
    'zh-CN': '更新状态只在标题栏下方的提示中显示一次。备份和安装期间，该提示保持可见，包括从设置中安装之前推迟的更新。',
    'zh-TW': '更新狀態只在標題列下方的提示中顯示一次。備份和安裝期間，該提示保持可見，包括從設定中安裝先前延後的更新。',
    ja: '更新状態はヘッダー下の通知に一度だけ表示されます。バックアップとインストール中も通知を表示し、設定から延期していた更新をインストールする場合も進行状況を確認できます。',
    ko: '업데이트 상태는 헤더 아래 알림에 한 번만 표시됩니다. 백업과 설치 중에도 알림이 유지되며, 설정에서 미뤄 둔 업데이트를 설치할 때도 진행 상황을 확인할 수 있습니다.',
  },
];
