import type { PrecedentContext, ReactionPrecedent } from './moleculeInspection';
import { similarityBand } from './reactionSimilarity';

/**
 * Reactions transcribed from the reaction schemes in the user's own textbooks (tools/scheme-scan):
 * each structure read from the drawing as SMILES and checked against the name and formula read with
 * it. The index has the Open Reaction Database's format, so the same Chemistry Studio tools look
 * routes up in it; a record id ("tb-…") resolves to its book, page and conditions through
 * records.json. Only confirmed and repaired records are indexed.
 */

export const TEXTBOOK_ID = /^tb-[0-9a-f]{32}$/;

/** One indexed record, as records.json holds it. */
export interface TextbookSchemeRecord {
  key: string;
  book: string;
  nodusId: string;
  /** 1-based PDF page; for an EPUB image, the chapter's position in the book. */
  page: number;
  kind: 'crop' | 'page' | 'image';
  reagents?: string | null;
  yield?: string | null;
  /** confirmed: every structure matches its name; repaired: a structure was replaced by the one its
   *  name and formula agreed on. */
  status: 'confirmed' | 'repaired';
  reaction: string;
}

/** A record ready to cite: where it is and, when the app has the book's text, a passage link to
 *  that page. */
export interface TextbookCitation {
  id: string;
  book: string;
  page: number;
  kind: TextbookSchemeRecord['kind'];
  reagents: string | null;
  yield: string | null;
  status: TextbookSchemeRecord['status'];
  link: string | null;
}

const MAX_CONDITIONS = 160;

function clip(text: string | null | undefined, max: number): string | null {
  const value = (text ?? '').replace(/\s+/g, ' ').trim();
  if (!value) return null;
  return value.length > max ? `${value.slice(0, max - 1)}…` : value;
}

export function textbookCitation(id: string, record: TextbookSchemeRecord, link: string | null = null): TextbookCitation {
  return {
    id,
    book: record.book,
    page: record.page,
    kind: record.kind,
    reagents: clip(record.reagents, MAX_CONDITIONS),
    yield: clip(record.yield, 60),
    status: record.status,
    link,
  };
}

/** "*Carey B*, p. 37" (or "chapter 12" for an EPUB image), linked when the page has a passage. */
export function textbookLocation(citation: TextbookCitation): string {
  const where = citation.kind === 'image' ? `chapter ${citation.page}` : `p. ${citation.page}`;
  const text = `*${citation.book}*, ${where}`;
  return citation.link ? `[${text}](${citation.link})` : text;
}

/** One citation line: location, conditions as drawn, yield, and whether a structure was repaired. */
export function formatTextbookCitation(citation: TextbookCitation): string {
  const parts = [textbookLocation(citation)];
  if (citation.reagents) parts.push(`conditions: ${citation.reagents}`);
  if (citation.yield) parts.push(`yield ${citation.yield}`);
  const note = citation.status === 'repaired' ? ' (a structure was corrected from its name and formula)' : '';
  return `${parts.join(' · ')}${note}`;
}

const TEXTBOOK_FOOTNOTE = '_Read from the scheme drawings in your textbooks by a vision model; each structure was checked against the name and formula read with it. Conditions are as drawn. Similarity compares which bonds change (DRFP, Tanimoto), not the molecules._';

/** The deterministic textbook-scheme section, one line block per route step; the model never
 *  authors it. Empty when no step and no target has a textbook record or a close one. */
export function formatTextbookPrecedents(
  precedent: ReactionPrecedent,
  cite: (ids: string[]) => TextbookCitation[],
  context?: Pick<PrecedentContext, 'queries' | 'target'>,
): string {
  const lines = ['### Known reactions (textbook schemes)',
    'This block is generated by the application, not by the model, from the reaction schemes in your textbooks.', ''];
  let found = false;
  const product = precedent.products[0];
  if (product && product.count > 0) {
    found = true;
    const name = context?.target?.name ? `**${context.target.name}** — ` : '';
    lines.push(`Target: ${name}\`${product.input}\` · made in ${product.count} textbook scheme(s).`, '');
  }
  const similarByInput = new Map(precedent.similar.map((item) => [item.input, item]));
  precedent.reactions.forEach((entry, position) => {
    if (entry.unchanged) return;
    const step = context?.queries[position]?.step ?? position;
    if (entry.count > 0) {
      const citations = cite(entry.samples ?? []).slice(0, 3);
      found = true;
      lines.push(`**Step ${step + 1}** — ✔ in ${entry.count} textbook scheme(s):`);
      lines.push(...(citations.length ? citations.map((citation) => `- ${formatTextbookCitation(citation)}`) : ['- (record details unavailable)']));
      lines.push('');
      return;
    }
    const closest = similarByInput.get(entry.input)?.neighbors[0];
    if (!closest || closest.similarity === undefined || closest.similarity < 0.4) return;
    found = true;
    const shown = closest.reaction ? ` \`${closest.reaction.length > 300 ? `${closest.reaction.slice(0, 299)}…` : closest.reaction}\`` : '';
    lines.push(`**Step ${step + 1}** — closest textbook reaction: ${Math.round(closest.similarity * 100)}% similar — ${similarityBand(closest.similarity)}.${shown}`, '');
  });
  if (!found) return '';
  lines.push(TEXTBOOK_FOOTNOTE);
  return `\n${lines.join('\n').trimEnd()}\n`;
}

/** Textbook reactions that make a molecule, for the pre-answer route evidence. */
export interface TextbookPreparation {
  molecule: string;
  reactions: Array<{ reaction: string; schemes: number; citations: string[] }>;
}

const PREPARATION_MOLECULES = 6;
const PREPARATION_REACTIONS = 3;
const PREPARATION_CITATIONS = 2;

/** Reads `reaction-disconnections` data from the textbook index: the recorded reactions that make
 *  each molecule (`madeBy`), each with its record ids resolved to citations. Template proposals are
 *  ignored: the textbook index has no retro templates. */
export function textbookPreparations(data: unknown, cite: (ids: string[]) => TextbookCitation[]): TextbookPreparation[] {
  const entries = (data as { disconnections?: unknown })?.disconnections;
  if (!Array.isArray(entries)) return [];
  const out: TextbookPreparation[] = [];
  for (const raw of entries) {
    const entry = raw as { target?: unknown; madeBy?: { reactions?: unknown } | null } | null;
    const molecule = typeof entry?.target === 'string' ? entry.target : '';
    const made = entry?.madeBy?.reactions;
    if (!molecule || !Array.isArray(made)) continue;
    const reactions: TextbookPreparation['reactions'] = [];
    for (const item of made) {
      const value = item as { reaction?: unknown; count?: unknown; samples?: unknown };
      if (typeof value.reaction !== 'string' || !value.reaction.includes('>>')) continue;
      const ids = Array.isArray(value.samples) ? value.samples.filter((id): id is string => typeof id === 'string' && TEXTBOOK_ID.test(id)) : [];
      const citations = cite(ids).slice(0, PREPARATION_CITATIONS).map(formatTextbookCitation);
      if (!citations.length) continue;
      reactions.push({ reaction: value.reaction.slice(0, 600), schemes: typeof value.count === 'number' ? value.count : citations.length, citations });
      if (reactions.length >= PREPARATION_REACTIONS) break;
    }
    if (reactions.length) out.push({ molecule, reactions });
    if (out.length >= PREPARATION_MOLECULES) break;
  }
  return out;
}
